x-bake:
  no-cache: false

services:
  front-end:
    build:
      context: ../Front-end
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - back-end
    restart: unless-stopped
    networks:
      - main-network

  back-end:
    build:
      context: ../Back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    container_name: back-end
    ports:
      - "8000:8000"
    volumes:
      - ./fonts:/fonts
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - main-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    networks:
      - main-network

  ollama-init:
    image: ollama/ollama
    container_name: ollama-init
    depends_on:
      - ollama
    volumes:
      - ./models:/models
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: >
      sh -c "
        sleep 5 &&
        ollama create law-exaone-7.8b-q6 -f /models/Modelfile
      "
    networks:
      - main-network
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    container_name: main-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
    networks:
      - main-network

  loki:
    image: grafana/loki:latest
    container_name: main-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - main-network

  promtail:
    image: grafana/promtail:latest
    container_name: main-promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - backend_logs:/app/logging:ro
    depends_on:
      - loki
      - back-end
    restart: unless-stopped
    networks:
      - main-network

  prometheus:
    image: prom/prometheus:latest
    container_name: main-prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - main-network

volumes:
  ollama_data:
  backend_logs:
  backend_uploads:
  grafana_data:
  loki_data:
  prometheus_data:

networks:
  main-network:
    driver: bridge